### ISSUE TITLE
Compilation does not succeed

### ISSUE THREAD

**Issue by Ditscheridou** [dajofrey/mipgen#1]
I cloned the project and tried to build it with the provided commands. Following error occurs: 

     `CMake Error at /snap/cmake/870/share/cmake-3.20/Modules/ExternalProject.cmake:2847 (message):
      No download info given for 'robin-map' and its source directory:

       /home/jonas/repositories/mipgen/third_party/robin-map/tnt

     is not an existing non-empty directory.  Please specify one of:

      * SOURCE_DIR with an existing non-empty directory
      * DOWNLOAD_COMMAND
      * URL
      * GIT_REPOSITORY
      * SVN_REPOSITORY
      * HG_REPOSITORY
      * CVS_REPOSITORY and CVS_MODULE`

**Comment by dajofrey** [comment]
Heyho,
thanks for letting me know!
Some paths were broken - should be fixed now.
